FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

RUN npm config set registry https://npm-mirror.gitverse.ru/
RUN npm install

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
